### ISSUE TITLE
Dependency on react

### ISSUE THREAD

**Issue by nealoke** [kennethjiang/react-file-download#10]
Hi, I just downloaded your project but it seems to also download react. Shouldn't the `dependency` in your `package.json` be replaced by `peerDependencies`? 

This makes it so that it checks if the peer dependency is present, if not provide error but not always download react when installing your project.
[
See example of react-select package.json](https://github.com/JedWatson/react-select/blob/master/package.json)

**Comment by kennethjiang** [comment]
With #9 merged should I close this issue? @nealoke

**Comment by nealoke** [comment]
@kennethjiang yes totally ;)
