### ISSUE TITLE
File not downloading?

### ISSUE THREAD

**Issue by nealoke** [kennethjiang/react-file-download#11]
I just pulled the new version and trying to make this work :)

Currently it is downloading something with the given name however it does not contain anything and looks like this (windows):

![image](https://cloud.githubusercontent.com/assets/17417414/25073459/8cdec7c0-22e7-11e7-875d-e3682c816b46.png)

I am supplying a url pointing to the file, am I doing this wrong? If so I think this would totally make sense to add to the component no?

**Sample url (what I am providing in the `data` argument)**
`http://localhost/papaver/app/dashboard/uploads/patients/files/wizer-brochure-versie1%40dcc4c3031202bcfd765ae0c8fd5fc3d8%23IazEdDEYO7.pdf` 

When I log this to the console and click it it opens the correct file in a seperate tab ;)

**Comment by kennethjiang** [comment]
Unfortunately this package doesn't work with Safari or IE. What browser are you using?

**Comment by nealoke** [comment]
@kennethjiang Aah why not? :o And i'm using chrome :/

**Comment by kennethjiang** [comment]
The reason why Safari or IE is not supported is that they don't support html5 `download` attribute, which is what this plugin is baed up.

I just tested the latest version and it still works. Can you provide a bit more info such as the code that's calling this plugin, and the network response coming back from the server?

**Comment by nealoke** [comment]
@kennethjiang sorry for the late answer, i basically used this in stead (which works fine in all browsers). I think I'll create a small github project for this 

```
var win = window.open('url', '_blank');
win.focus();
```

**Comment by kennethjiang** [comment]
sounds good!
