### ISSUE TITLE
old peer dependencies still on npm

### ISSUE THREAD

**Issue by psachs21** [kennethjiang/react-file-download#15]
I've freshly installed react-file-download and it says it has the wrong peer dependencies:

`warning "react-file-download@0.3.3" has incorrect peer dependency "react@^0.14.7 || ^0.15.0".`

Since the source code no longer has these dependencies, i can only imagine that the changes have not been published properly.

**Comment by kennethjiang** [comment]
My apology for the sloppiness.

Just published 0.3.4.

**Comment by psachs21** [comment]
Thanks for the quick response!
