### ISSUE TITLE
Consider revokeObjectURL?

### ISSUE THREAD

**Issue by lmannering** [kennethjiang/react-file-download#16]
I considered submitting a PR for this, but would be interested to understand why the author has chosen not to implement revokeObjectURL to improve memory usage (after removing the tempLink):

windowUrl.revokeObjectURL(blobURL);

As per:
https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

**Comment by kennethjiang** [comment]
Sorry for the delay!

I wasn't aware of `revokeObjectURL`. Sounds like something I should have done to avoid potential memory leak. Please go ahead to send a PR.
