### ISSUE TITLE
Safari on Mac issue

### ISSUE THREAD

**Issue by tymochko** [kennethjiang/react-file-download#5]
Hello,
we are experiencing weird behaviour on Safari on Mac:
instead of file start to download - blob content opens up in new tab and looks like bunch of non-readable symbols.
Rest of browsers works just fine.

**Comment by kennethjiang** [comment]
sorry for the delay. will take a look when I get a chance.

**Comment by kennethjiang** [comment]
I did a little research and it seems that Safari doesn't support `download` attribute, which is why it opens the content instead of triggering a download. See some of the online discussions here: https://forums.developer.apple.com/thread/11837

Have you found any solutions? @tymochko

**Comment by tymochko** [comment]
@kennethjiang, unfortunately it's true. So we had to switch to solution of downloading file via api from server using
`<a href="/api/...">Donwload file</a>`

**Comment by kennethjiang** [comment]
Right... I'm lucky enough that I don't have to deal with Safari. Keep me posted in case you find a JS solution on Safari.
