### ISSUE TITLE
File get renamed after download differently in every browser (colon).

### ISSUE THREAD

**Issue by leniartek** [kennethjiang/react-file-download#8]
When I trigger a download with a name containing a colon it gets renamed differently for every browser.
`fileDownload(data, "file:name.json");`

Chrome 53
> file-name.json

IE 11
> file_name.json

I know that colon cannot be saved in a file name but I expect file to be always named the same in every browser.

**Comment by kennethjiang** [comment]
I think this is just nuances of handling special characters in different browsers. And it'll be the case for any file download mechanism. I don't think I can do anything to 'fix' this, but let me know if you have some ideas.
